spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://ep-gentle-sky-aqy1ow0m-pooler.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.write-dates-as-timestamps=false